// [ MSTE STAGE DATA GENERATED BY PARSER v4.0 ]
const STAGE_DATA = [
    // === LEVEL 1 ===
    {
        level: 1,
        spawnList: [
            { row: 0, type: 'BGM', val: 'test_bgm_01.mp3' },
            { row: 0, type: 'SPEED', val: 100 },
            { row: 0, type: 'SYMBOL', val: ['+'] },
            { row: 0, type: 'NUMBER', val: [1, 2, 3] },
            { row: 0, type: 'PRINT', text: "우주선을 움직여 숫자를 먹고 적을 향해 발사하세요!", duration: 2 },
            { row: 0, col: 1, hp: 2 },
            { row: 1, col: 4, hp: 4 },
            { row: 2, col: 2, hp: 3 },
            { row: 3, col: 7, hp: 2 },
            { row: 4, type: 'ITEM', col: 2, val: 'HEAVY_ROTATION' },
			{ row: 4, type: 'ITEM', col: 4, val: 'TIME_STOP' },
			{ row: 4, type: 'ITEM', col: 6, val: 'EASY_BUSY' },
            { row: 5, col: 5, hp: 1 },
            { row: 6, col: 1, hp: 3 },
            { row: 8, col: 4, hp: 1 },
            { row: 9, type: 'PRINT', text: "HP가 높은 적은 +를 넣어 수식을 만들어 공격해 보세요.", duration: 2 },
            { row: 9, col: 3, hp: 6 },
            { row: 10, col: 4, hp: 8 },
            { row: 11, col: 6, hp: 4 },
            { row: 12, type: 'SPEED', val: 50 },
            { row: 12, type: 'PRINT', text: "이제 보스가 등장합니다. 더 긴 수식을 만들어 보세요.", duration: 2 },
            { row: 12, col: 2, hp: 5 },
            { row: 12, col: 4, hp: 10, isBoss: true },
            { row: 12, col: 6, hp: 5 },
        ]
    }

];
